services:
  postgres:
    container_name: clica-la_db-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: clica-la_db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
